/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/dashboard/': RouteRecordInfo<'/dashboard/', '/dashboard', Record<never, never>, Record<never, never>>,
    '/dashboard/farmers/': RouteRecordInfo<'/dashboard/farmers/', '/dashboard/farmers', Record<never, never>, Record<never, never>>,
    '/dashboard/records/': RouteRecordInfo<'/dashboard/records/', '/dashboard/records', Record<never, never>, Record<never, never>>,
    '/dashboard/records/[id]': RouteRecordInfo<'/dashboard/records/[id]', '/dashboard/records/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/dashboard/records/components/RecordsTable': RouteRecordInfo<'/dashboard/records/components/RecordsTable', '/dashboard/records/components/RecordsTable', Record<never, never>, Record<never, never>>,
    '/dashboard/records/components/RecordsTableDeleteButton': RouteRecordInfo<'/dashboard/records/components/RecordsTableDeleteButton', '/dashboard/records/components/RecordsTableDeleteButton', Record<never, never>, Record<never, never>>,
    '/dashboard/records/create': RouteRecordInfo<'/dashboard/records/create', '/dashboard/records/create', Record<never, never>, Record<never, never>>,
    '/dashboard/staffs/': RouteRecordInfo<'/dashboard/staffs/', '/dashboard/staffs', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
  }
}
