export const municipalities = [
  {
    name: 'Sariaya',
    barangays: [
      'Antipolo',
      'Balubal',
      'Barangay 1 (Poblacion)',
      'Barangay 2 (Poblacion)',
      'Barangay 3 (Poblacion)',
      'Barangay 4 (Poblacion)',
      'Barangay 5 (Poblacion)',
      'Barangay 6 (Poblacion)',
      'Bignay 1',
      'Bignay 2',
      'Bucal',
      'Canda',
      'Castañas',
      'Concepcion Banahaw',
      'Concepcion 1',
      'Concepcion Palasan',
      'Concepcion Pinagbakuran',
      'Gibanga',
      'Guisguis-San Roque',
      'Guisguis-Talon',
      'Janagdong 1',
      'Janagdong 2',
      'Limbon',
      'Lutucan 1',
      'Lutucan Bata',
      'Lutucan Malabag',
      'Mamala 1',
      'Mamala 2',
      'Manggalang 1',
      'Manggalang Tulo-tulo',
      'Manggalang-Bantilan',
      'Manggalang-Kiling',
      'Montecillo',
      'Morong',
      'Pili',
      'Sampaloc 1',
      'Sampaloc 2',
      'Sampaloc Bogon',
      'Sampaloc Santo Cristo',
      'Talaan Aplaya',
      'Talaan Pantoc',
      'Tumbaga 1',
      'Tumbaga 2',
    ],
  },
  {
    name: 'Candelaria',
    barangays: [
      'Poblacion',
      'Buenavista East',
      'Buenavista West',
      'Bukal Norte',
      'Bukal Sur',
      'Kinatihan I',
      'Kinatihan II',
      'Malabanban Norte',
      'Malabanban Sur',
      'Mangilag Norte',
      'Mangilag Sur',
      'Masalukot I',
      'Masalukot II',
      'Masalukot III',
      'Masalukot IV',
      'Masalukot V',
      'Masin Norte',
      'Masin Sur',
      'Mayabobo',
      'Pahinga Norte',
      'Pahinga Sur',
      'San Andres',
      'San Isidro',
      'Santa Catalina Norte',
      'Santa Catalina Sur',
    ],
  },
];
