/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseAlert: typeof import('./components/base/alert/BaseAlert.vue')['default']
    BaseButton: typeof import('./components/base/button/BaseButton.vue')['default']
    BaseForm: typeof import('./components/base/form/BaseForm.vue')['default']
    BaseInput: typeof import('./components/base/input/BaseInput.vue')['default']
    BasePagination: typeof import('./components/base/pagination/BasePagination.vue')['default']
    BaseSelect: typeof import('./components/base/select/BaseSelect.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
