/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/dashboard/': RouteRecordInfo<'/dashboard/', '/dashboard', Record<never, never>, Record<never, never>>,
    '/dashboard/farmers/': RouteRecordInfo<'/dashboard/farmers/', '/dashboard/farmers', Record<never, never>, Record<never, never>>,
    '/dashboard/farmers/[id]': RouteRecordInfo<'/dashboard/farmers/[id]', '/dashboard/farmers/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/dashboard/farmers/components/create-form/FarmerCreateForm': RouteRecordInfo<'/dashboard/farmers/components/create-form/FarmerCreateForm', '/dashboard/farmers/components/create-form/FarmerCreateForm', Record<never, never>, Record<never, never>>,
    '/dashboard/farmers/components/table/FarmersTable': RouteRecordInfo<'/dashboard/farmers/components/table/FarmersTable', '/dashboard/farmers/components/table/FarmersTable', Record<never, never>, Record<never, never>>,
    '/dashboard/farmers/components/table/FarmersTableDeleteButton': RouteRecordInfo<'/dashboard/farmers/components/table/FarmersTableDeleteButton', '/dashboard/farmers/components/table/FarmersTableDeleteButton', Record<never, never>, Record<never, never>>,
    '/dashboard/farmers/components/update-form/FarmerUpdateForm': RouteRecordInfo<'/dashboard/farmers/components/update-form/FarmerUpdateForm', '/dashboard/farmers/components/update-form/FarmerUpdateForm', Record<never, never>, Record<never, never>>,
    '/dashboard/farmers/new': RouteRecordInfo<'/dashboard/farmers/new', '/dashboard/farmers/new', Record<never, never>, Record<never, never>>,
    '/dashboard/records/': RouteRecordInfo<'/dashboard/records/', '/dashboard/records', Record<never, never>, Record<never, never>>,
    '/dashboard/records/[id]': RouteRecordInfo<'/dashboard/records/[id]', '/dashboard/records/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/dashboard/records/components/create-form/RecordCreateForm': RouteRecordInfo<'/dashboard/records/components/create-form/RecordCreateForm', '/dashboard/records/components/create-form/RecordCreateForm', Record<never, never>, Record<never, never>>,
    '/dashboard/records/components/table/RecordsTable': RouteRecordInfo<'/dashboard/records/components/table/RecordsTable', '/dashboard/records/components/table/RecordsTable', Record<never, never>, Record<never, never>>,
    '/dashboard/records/components/table/RecordsTableDeleteButton': RouteRecordInfo<'/dashboard/records/components/table/RecordsTableDeleteButton', '/dashboard/records/components/table/RecordsTableDeleteButton', Record<never, never>, Record<never, never>>,
    '/dashboard/records/components/update-form/RecordUpdateForm': RouteRecordInfo<'/dashboard/records/components/update-form/RecordUpdateForm', '/dashboard/records/components/update-form/RecordUpdateForm', Record<never, never>, Record<never, never>>,
    '/dashboard/records/new': RouteRecordInfo<'/dashboard/records/new', '/dashboard/records/new', Record<never, never>, Record<never, never>>,
    '/dashboard/staffs/': RouteRecordInfo<'/dashboard/staffs/', '/dashboard/staffs', Record<never, never>, Record<never, never>>,
    '/dashboard/staffs/[id]': RouteRecordInfo<'/dashboard/staffs/[id]', '/dashboard/staffs/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/dashboard/staffs/components/create-form/StaffCreateForm': RouteRecordInfo<'/dashboard/staffs/components/create-form/StaffCreateForm', '/dashboard/staffs/components/create-form/StaffCreateForm', Record<never, never>, Record<never, never>>,
    '/dashboard/staffs/components/table/StaffsTable': RouteRecordInfo<'/dashboard/staffs/components/table/StaffsTable', '/dashboard/staffs/components/table/StaffsTable', Record<never, never>, Record<never, never>>,
    '/dashboard/staffs/components/table/StaffsTableDeleteButton': RouteRecordInfo<'/dashboard/staffs/components/table/StaffsTableDeleteButton', '/dashboard/staffs/components/table/StaffsTableDeleteButton', Record<never, never>, Record<never, never>>,
    '/dashboard/staffs/components/update-form/StaffUpdateForm': RouteRecordInfo<'/dashboard/staffs/components/update-form/StaffUpdateForm', '/dashboard/staffs/components/update-form/StaffUpdateForm', Record<never, never>, Record<never, never>>,
    '/dashboard/staffs/new': RouteRecordInfo<'/dashboard/staffs/new', '/dashboard/staffs/new', Record<never, never>, Record<never, never>>,
  }
}
